apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  index .Values.services "discovery-server" "name" }}
  labels:
    app: {{  index .Values.services "discovery-server" "name" }}
spec:
  replicas: {{  index .Values.services "discovery-server" "replicaCount" }}
  selector:
    matchLabels:
      app: {{  index .Values.services "discovery-server" "name" }}
  template:
    metadata:
      labels:
        app: {{  index .Values.services "discovery-server" "name" }}
    spec:
      containers:
      - name: {{  index .Values.services "discovery-server" "name" }}
        image: '{{ index .Values.services "discovery-server" "image" "name" }}:{{ index .Values.services "discovery-server" "image" "tag" }}'
        ports:
        - containerPort: {{  index .Values.services "discovery-server" "port" }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{  index .Values.services "discovery-server" "name" }}
spec:
  selector:
    app: {{  index .Values.services "discovery-server" "name" }}
  ports:
    - protocol: TCP
      port: {{ index .Values.services "discovery-server" "port" }}
      targetPort: {{ index .Values.services "discovery-server" "port" }}
  type: ClusterIP
