apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.services.mysql.secretName }}
type: Opaque
data:
  mysql-user: {{ .Values.services.mysql.credentials.user | b64enc }}
  mysql-password: {{ .Values.services.mysql.credentials.password | b64enc }}
  mysql-root-password: {{ .Values.services.mysql.credentials.rootPassword | b64enc }}