apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  index .Values.services "visits-service" "name" }}
  labels:
    app: {{  index .Values.services "visits-service" "name" }}
spec:
  replicas: {{  index .Values.services "visits-service" "replicaCount" }}
  selector:
    matchLabels:
      app: {{  index .Values.services "visits-service" "name" }}
  template:
    metadata:
      labels:
        app: {{  index .Values.services "visits-service" "name" }}
    spec:
      containers:
      - name: {{  index .Values.services "visits-service" "name" }}
        image: '{{ index .Values.services "visits-service" "image" "name" }}:{{ index .Values.services "visits-service" "image" "tag" }}'
        ports:
        - containerPort: {{  index .Values.services "visits-service" "port" }}
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-user
        - name: USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-password

---
apiVersion: v1
kind: Service
metadata:
  name: {{  index .Values.services "visits-service" "name" }}
spec:
  selector:
    app: {{  index .Values.services "visits-service" "name" }}
  ports:
    - protocol: TCP
      port: {{ index .Values.services "visits-service" "port" }}
      targetPort: {{ index .Values.services "visits-service" "port" }}
  type: ClusterIP
